---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.3
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.369
    hooks:
      - id: pyright
        additional_dependencies: [fastapi<=0.95, pyhumps]
  - repo: https://github.com/lyz-code/yamlfix/
    rev: main
    hooks:
      - id: yamlfix
